
const Discord = require('discord.js');
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();

const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();

const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
const Twana= new Discord.Client();
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
Twana.login("");
